### ISSUE TITLE
Patrón Abstract Factory

### ISSUE THREAD

**Issue by domorales** [NielzosFilms/2D-Top-Down-Game#8]
El Programa solo cuenta con una clase World  que genera varios escenarios dependiendo de las variables que se ingresen, esto  hace que el código no pueda ser sostenible ya que al añadir nuevos escenarios, es inevitable ingresar nuevas condiciones y modificar varias partes del código existente. Por lo que se recomienda usar el patrón Abstract Factory, que permite agrupar familias de objetos, y tener un acoplamiento débil entre escenario y el resto del código.

![TareaPatrones20DIC - Dilan AbstractFactory](https://user-images.githubusercontent.com/73241625/102725721-cdf18180-42e6-11eb-90c3-2e663678b471.png)
Se cuenta con varias clases que representan escenarios concretos lo que hace posible que se cumpla el principio de Responsabilidad Única. Además, al ingresar nuevos escenarios no es necesario modificar los existentes, permitiendo que se cumpla el principio de Abierto/Cerrado.

**Comment by NielzosFilms** [comment]
Thank you for your explanation, it would have been nice to get in in English tho.
I am going to close this because this this system isn't used anymore and thus is irrelevant.
