### ISSUE TITLE
Adapter Method

### ISSUE THREAD

**Issue by aardreye** [NielzosFilms/2D-Top-Down-Game#9]
La interfaz UpdateAble implementa el método update() que no recibe parámetro, update() actualiza una variable de acuerdo a un condicional, pero si ahora la actualización de datos esta basada en una interfaz que requiere el ingreso del nuevo valor hay que adaptar esa interfaz al nuevo método implementado.
![TareaPatrones20DIC - Aarón Adapter](https://user-images.githubusercontent.com/73242676/102757564-82b78d00-433f-11eb-9535-502839cb4231.png)

**Comment by NielzosFilms** [comment]
Thank you for your explanation, it would have been nice to get in in English tho.
I am going to close this because this this system isn't used anymore and thus is irrelevant.
